### ISSUE TITLE
Kleiner css Verschreiber bei parallax

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/Modulsammlung#105]
![Bildschirmfoto 2019-07-08 um 09 14 41](https://user-images.githubusercontent.com/45007596/60790121-050abc00-a161-11e9-9c55-a59b5e3ea47d.png)

**Comment by olien** [comment]
Danke. werde ich fixen (wobei ein PR willkommen ist :-))

**Comment by Geri2017** [comment]
Ich habe schon nach dem Code gesucht, aber nicht gefunden :-(

**Comment by skerbis** [comment]
@Geri2017 https://github.com/FriendsOfREDAXO/Modulsammlung/blob/674d7cfad531e0cb1e67a66409bff028af33249a/lib/module/0105_parallax_skrollr/styles_scss.inc#L1

Die Volltextsuche in Github hilft Dir auch dabei

**Comment by olien** [comment]
Wobei die Class im Output auch so heisst. Also wenn dann beides korrigieren :-))

https://github.com/FriendsOfREDAXO/Modulsammlung/blob/674d7cfad531e0cb1e67a66409bff028af33249a/lib/module/0105_parallax_skrollr/output.inc#L51

**Comment by Geri2017** [comment]
WTF?
![Bildschirmfoto 2019-07-08 um 13 10 35](https://user-images.githubusercontent.com/45007596/60805904-cfc29600-a181-11e9-9ffa-3d08eb5dfe30.png)

**Comment by skerbis** [comment]
Kurz oben links auf Master stellen 
- Dann geht's -

**Comment by Geri2017** [comment]
Danke für den Tip mit `master`.
Man lernt jeden Tag dazu :-)
Alles erledigt!

**Comment by skerbis** [comment]
Du kannst das issue automatisch closen lassen wenn du im PR fixes link zum issue eingibst. 
Dann wird das issue geschlossen, sobald gemerged wurde

**Comment by olien** [comment]
Hallo @Geri2017 ich habe die PRs gemerkt. Danke dafür.
Um es rund zu machen muß noch 

* die Versionsnummer erhöht werden (auf 4.13.3)
* ein Eintrag im Chagelog geschrieben werden
* ein neues Release gemacht werden und
* die neue Version in den Installer geladen werden

Magst Du das durchspielen oder soll ich das machen (dann aber frühestens am WE :-))

LG
Oliver

**Comment by Geri2017** [comment]
Versionsnummer -> erledigt
Eintrag im Changelog -> erledigt
`neues Release gemacht` und `neue Version in den Installer geladen` ???? 
Keine Ahnung wie man das macht, aber ich lerne gern dazu :-)

**Comment by olien** [comment]
Top. Die PRs kannst Du gerne übernehmen...

Der Rest steht hier: https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io

**Comment by olien** [comment]
Ist das erledigt? dann kann das hier zu?

**Comment by skerbis** [comment]
scheint ja so
