### ISSUE TITLE
Kleiner Fehler im Beispielmodul "Modul: 0036 - Text / Kontaktformular-Generator"

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/Modulsammlung#112]
Das vorausgefüllte Beispielformular hat beim Spamschutz den Eintrag
`info|Geben Sie bitte nochmal Ihren Vornamen ein
text|Nachname|1|||check`
Es sollte aber heißen
`info|Geben Sie bitte nochmal Ihren Vornamen ein
text|Vorname|1|||check` 
Oder?

**Comment by olien** [comment]
@skerbis War das "Deines"?

**Comment by skerbis** [comment]
Ja ...

**Comment by skerbis** [comment]
hmm ... ist im Quellcode schon korrigiert? Evtl. noch nicht im Release?

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/Modulsammlung/releases/tag/4.13.4
