### ISSUE TITLE
E-Mail des Besuchers (sender) wird nicht als Platzhalter übergeben

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/Modulsammlung#113]
`%Besuchermail% (wird durch sender gesetzt)`
funktioniert nicht in der Bestätigungsmail.

**Comment by skerbis** [comment]
%sender%

**Comment by ansichtsache** [comment]
Leider nein: `%Absender%` liefert die im Modul eingetragene "Absenderadresse für die Bestätigungs-E-Mail" – ich möchte aber die im Formular im Frontend eingetragene E-Mail des Nutzers haben, die in der Zeile "E-Mail" eingetragen wird. Generiert im Modul durch `email|E-Mail|1|||sender`.

**Comment by skerbis** [comment]
Ach so, Update folgt

**Comment by skerbis** [comment]
fixed

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/Modulsammlung/releases/tag/4.13.4

**Comment by ansichtsache** [comment]
besten dank!
