### ISSUE TITLE
0050 - Bildergalerie (Unite Gallery) ist fehlerhaft / es wird nicht die aktuelle Version installiert

### ISSUE THREAD

**Issue by w-sk** [FriendsOfREDAXO/Modulsammlung#125]
Fehler: Die ersten 12 Vorschaubilder einer "Tiles Grid"-Galerie werden im Frontend in einem Block angezeigt – so weit, so gut. Wenn dann weiter "geblättert" wird, erscheinen pro "Seite" nur noch jeweils 4, und die nächsten 8 werden nicht angezeigt.
Das Problemchen taucht auf mit der Version der Unitegallery, die über das AddOn von Github kopiert wird (das ist derzeit offenbar die 1.7.18) – es taucht nicht mehr auf mit der Version, die von unitegallery.net heruntergeladen werden kann (1.7.45).

**Comment by olien** [comment]
Ist erledigt. Danke sehr
