### ISSUE TITLE
0036 - Text / Kontaktformular-Generator (do form!) - syntax error, unexpected '{' in Line 461

### ISSUE THREAD

**Issue by OnSerious** [FriendsOfREDAXO/Modulsammlung#130]
Versions REDAXO 5.14.1, PHP 7.4.32, MariaDB 10.5.17

**ParseError:** syntax error, unexpected '{'
**File:** 0036 - Text / Kontaktformular-Generator (do form!)
**Line:** 461
Codesnippet: 

> 460     if(!isset($element[4]
    461       {
    462           $element[4] = '';
    463       }
    464        $formoutput[] = $hidden . '
    465         <div class="'.$form_field_wrp.' ' . $warnblock["el_" . $i] . '"> <span class="checkspan"><label ' . $warning["el_" . $i] . ' for="el_' . $i . '" >' . $element[1] . $req . '</label>
                <input type="checkbox" title="' . $element[4]  . '" class="uk-checkbox" name="FORM[' . $form_ID . '][el_' . $i . ']" id="el_' . $i . '"value="X" ' . $cchecked . ' /></span></div>';
   466         break;

**Fehler kann wie folgt an meinem Redaxo nachgebaut werden, und wird immer getriggert:** 
- Neuer Artikel wird angelegt
- Modul 0036 - Text / Kontaktformular-Generator (do form!) wird per Block in Content geladen
- Formularfelder werden im Grunde nicht modifiziert (Fehler beim Check am Ende - geben Sie den Vornamen ein, wird gefixt, da dort Name drin steht als Checkfeld) 
- E-Mail Adresse, Betreff, Button Beschreibung "Anfrage absenden", sowie eine Erfolgsmeldung nach Druck wird eingegeben. Beim speichern des Blockes, sofortige Fehlermeldung, Artikel kann nicht mehr geöffnet werden, da sofort die Meldung erscheint.

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.32     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.5.17 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/106.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | yes              |

| Packages            |             |
| ------------------: | :---------- |
|             adminer | 1.9.2       |
|              backup | 2.8.2       |
|            be_style | 3.1.0       |
| be_style/customizer | 3.1.0       |
|     be_style/redaxo | 3.1.0       |
|     consent_manager | 3.0.8       |
|               fonts | 0.0.1-alpha |
|             install | 2.10.0      |
|       media_manager | 2.13.0      |
|           mediapool | 2.12.0      |
|            metainfo | 2.9.0       |
|       modulsammlung | 4.15.3      |
|           phpmailer | 2.11.2      |
|             project | dev         |
|           structure | 2.14.1      |
|   structure/content | 2.14.1      |
|            tinymce5 | 1.2.15      |
|               users | 2.9.0       |
|               yform | 4.0.4       |
|         yform/email | 4.0.4       |
|       yform/manager | 4.0.4       |
|          yform/rest | 4.0.4       |
|         yform/tools | 4.0.4       |
|         yform_field | 2.0.1       |

</details>

**Comment by olien** [comment]
@skerbis vielleicht?

**Comment by skerbis** [comment]
In 460 fehlte ein )
