### ISSUE TITLE
Call to a member function getName() on null

### ISSUE THREAD

**Issue by Daimonion1980** [FriendsOfREDAXO/Modulsammlung#133]
Ich habe auf einer Webseite das Modulsammlungsplugin im Einsatz und das Modul 0010 - Text / Bild / Video / Link (1-4 Spalten) installiert. Nach einem länger fälligen Update bin ich nun auf den aktuellen Versionen der Software und des Webservers unterwegs.

Modulsammlung v4.15.4
Redaxo Core v5.15.1

Leider wirft mir das Modul nun einen Fehler, wenn ich die dazugehörige Strukturseite öffne.
Das Modul habe ich nicht verändert und auch eine Neuinstallation des Moduls brachte keine Codeänderung. 
Bevor ich selbst anfange das Modul auseinander zu nehmen, wollte ich mal fragen was da das Problem sein könnte.
Die betreffende Codestelle verlinke ich mal https://github.com/FriendsOfREDAXO/Modulsammlung/blob/be08e0a25bc369123b61c523103059e0b08de574/lib/module/0010_text_bild_video_link/output.inc#L104C12-L104C16

**Error:** Call to a member function getName() on null
**File:** rex:///module/19/output
**Line:** 104

<details>
<summary>Stacktrace</summary>

| Function                                           | File                                                                       | Line     |
| -------------------------------------------------- | -------------------------------------------------------------------------- | -------- |
| require                                            | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 487      |
| rex_article_content_base->{closure}                | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 489      |
| rex_article_content_base->getStreamOutput          | redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php | 269      |
| rex_article_content_editor->getWrappedModuleOutput | redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php | 82       |
| rex_article_content_editor->outputSlice            | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 686      |
| rex_article_content_base->renderSlices             | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 402      |
| rex_article_content_base->getArticle               | redaxo/src/addons/structure/plugins/content/lib/article_content.php        | 106      |
| rex_article_content->getArticle                    | redaxo/src/addons/structure/plugins/content/pages/content.edit.php         | 35       |
| require                                            | redaxo/src/core/lib/packages/package.php                                   | 233      |
| rex_package->includeFile                           | redaxo/src/core/lib/be/controller.php                                      | 503      |
| rex_be_controller::{closure}                       | redaxo/src/core/lib/util/timer.php                                         | 56       |
| rex_timer::measure                                 | redaxo/src/core/lib/be/controller.php                                      | 504      |
| rex_be_controller::includePath                     | redaxo/src/core/lib/be/controller.php                                      | 453      |
| rex_be_controller::includeCurrentPageSubPath       | redaxo/src/addons/structure/plugins/content/pages/content.php              | 430      |
| require                                            | redaxo/src/core/lib/packages/package.php                                   | 233      |
| rex_package->includeFile                           | redaxo/src/core/lib/be/controller.php                                      | 503      |
| rex_be_controller::{closure}                       | redaxo/src/core/lib/util/timer.php                                         | 56       |
| rex_timer::measure                                 | redaxo/src/core/lib/be/controller.php                                      | 504      |
| rex_be_controller::includePath                     | redaxo/src/core/lib/be/controller.php                                      | 436      |
| rex_be_controller::includeCurrentPage              | redaxo/src/core/backend.php                                                | 241      |
| require                                            | redaxo/src/core/boot.php                                                   | 155      |
| require                                            | redaxo/index.php                                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.1.16, MySQL 5.7.37)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.16     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.37 |
| Character set | utf8         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/114.0.0.0 |
|      Protocol | HTTP/2.0         |
|         HTTPS | yes              |

| Packages            |            |
| ------------------: | :--------- |
|              backup | 2.9.0      |
|            be_style | 3.2.0      |
| be_style/customizer | 3.2.0      |
|     be_style/redaxo | 3.2.0      |
|        cache_warmup | 4.0.0      |
|           demo_base | 3.1.0      |
|          iconpicker | 1.1.0      |
|             install | 2.11.1     |
|            markitup | 3.7.4      |
|              mblock | 3.4.12     |
|       media_manager | 2.14.0     |
|           mediapool | 2.13.0     |
|            metainfo | 2.10.0     |
|               mform | 7.3.0      |
|       modulsammlung | 4.15.4     |
|           phpmailer | 2.12.0     |
|             project | dev        |
|           redactor2 | 4.0.3      |
|               sprog | 1.5.1      |
|           structure | 2.15.0     |
|   structure/content | 2.15.0     |
|            uploader | 2.4.1      |
|               users | 2.10.0     |
|               yform | 4.1.1      |
|          yform/docs | 3.3.1      |
|         yform/email | 4.1.1      |
|       yform/manager | 4.1.1      |
|            yrewrite | 2.10.0     |

</details>

**Comment by olien** [comment]
Das Modul wird in der nächsten Version des Addons entfernt (ist einfach zu aufwändig das Teil)
