### ISSUE TITLE
Weitere Einstellungen für ID & Klassen

### ISSUE THREAD

**Issue by elricco** [FriendsOfREDAXO/Modulsammlung#45]
Schön wäre, wenn bei (fast) allen Modulen es "Weitere Einstellungen" gäbe mit Eingabefeldern für eine ID und zusätzliche individuelle Klassen. So kann man ein Modul mehrfach verwenden, es aber immer anders aussehen lassen (oder es ansprechen).

**Comment by olien** [comment]
Bei welchen Modulen hättest du es gerne?

**Comment by elricco** [comment]
Ich fänd es beim Slider und bei der (Unite) Gallery ganz schön. Beim Slider hatte ich es mir schon erweitert um Klassen um verschieden gestylte Slider zu realisieren (bzw. den Text auf den Slides verschieden zu positionieren) und bei der Gallery wäre es ebenfalls ganz schön. (Da ich noch nicht alle Module durchgeschaut / genutzt habe, kann ich dir nur vom aktuellen Fall berichten).

**Comment by olien** [comment]
ok. baue ich ein... evtl. macht das bei allen modulen sinn wo ich schon ein bischen html ausgebe. also fast alle bis auf die minibeispiele...

**Comment by elricco** [comment]
Ja, genau. Hatte ich in der 4er hinterher auch fast in allen Modulen. Habe mir immer die 20 für die $rexnames freigehalten, die 19 für die ID und die 18 für die Klassen.

**Comment by olien** [comment]
Sollte erledigt sein.
