### ISSUE TITLE
Download Hilfstemplate geht kürzer mit

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/Modulsammlung#51]
rex_response::sendFile($file,$contenttype, $contentDisposition = 'attachment');
Siehe: http://www.redaxo.org/docs/master/source-class-rex_response.html#70-102

**Comment by olien** [comment]
Würde mich über ein Beispiel freuen .-)

**Comment by skerbis** [comment]
Ungefähr so: 

`
$fileName = rex_get('fileName', 'string');

if (!file_exists(rex_path::media($fileName)))
{
	rex_redirect(1);
}
// Redaxo Outputbuffer löschen
rex_response::cleanOutputBuffers();

// Ausgabe des Mediums
$file = rex_path::media().$fileName;
if (file_exists($file)) {
   $contenttype = 'application/octet-stream';
   rex_response::sendFile($file,$contenttype, $contentDisposition = 'attachment');
   exit();`

**Comment by skerbis** [comment]
Wobei ich mir nicht sicher bin ob exit(); noch benötigt wird

**Comment by alexplusde** [comment]
Warum nicht ein passendes MediaManger-Profil anlegen?

**Comment by olien** [comment]
Gerne. Gibt es da etwas?

**Comment by alexplusde** [comment]
## Pflicht

* Download-Typ anlegen: 
* Name: `download`,
* Effekt: `header`, 
* Parameter: `download`, `no-cache`

dann kann man über das bekannte Schema `/imagetypes/download/dateiname.pdf` auch Dateien durch den Medienmanager geschleust herunterladen. 

## Kür

Wem der Pfad nicht gefällt, der wandelt die .htaccess noch ab:

```
RewriteRule ^media/([^/]*)/([^/]*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2&%{QUERY_STRING} [B]
```
Download erfolgt dann über `/media/download/dateiname.pdf`

Oder:
RewriteRule ^download/([^/]*) %{ENV:BASE}/index.php?rex_media_type=download&rex_media_file=$1&%{QUERY_STRING} [B]
```
Download erfolgt dann direkt über `/download/dateiname.pdf`

**Comment by olien** [comment]
OK: Ich bin blind... werde ich so ändern... Danke!

**Comment by alexplusde** [comment]
https://github.com/FriendsOfREDAXO/Modulsammlung/issues/47

**Comment by skerbis** [comment]
oder so

**Comment by olien** [comment]
Erledigt in der Version 4.7.4. Danke!

**Comment by alexplusde** [comment]
:)

**Comment by olien** [comment]
Hey, ging doch fix...
