### ISSUE TITLE
Addon umbenennen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/Modulsammlung#54]
Der Name könnte den REX-Prefix loswerden, und passenderweise ist der Addonkey bereits `modulsammlung`. Allerdings sagt @olien zurecht: Es ist nicht zwangsläufig auf Module beschränkt, sondern es könnten z. B. auch Templates hinzukommen.

Deshalb die Frage in den Raum: Wollen wir es umbenennen? Und wie?

Vorschlag nach Slack-Diskussion: `schnipsel` :)

**Comment by skerbis** [comment]
Schnipsel passt irgendwie nicht wirklich, da es schon sehr ausgereifte und häufig sofort nutzbare Module sind. 
Codesammlung vielleicht?

**Comment by olien** [comment]
First Blood
Module & Templates
Starter Pack
Clean Install
Module und mehr
Codesammlung
Basics Installer
...

**Comment by skerbis** [comment]
An Starter Pack habe ich auch gedacht. Sorgt aber für zu viel Support bei Anfängern, denke ich. Es suggeriert zu sehr eine Out of the Box Lösung - findest Du nicht?

**Comment by tbaddade** [comment]
- Rexarium

**Comment by olien** [comment]
@skerbis Ja,. Stimmt.
@tbaddade ernsthaft? Mir wäre alles recht...

**Comment by olien** [comment]
Wie wäre es mit

`installable`

**Comment by schuer** [comment]
Oder `Beispielsammlung`. Deutscher Begriff, weil das Addon nicht danach scheint, als würde es allzu bald internationalisiert. Sehr viel Content drin, alles deutschsprachig aufgesetzt. Dann könnte es auch gut einen deutschsprachigen Namen bekommen, finde ich.

**Comment by olien** [comment]
ok. Dann vielleicht eher... 

`Module & Templates`

**Comment by schuer** [comment]
Ich finde ja nach all der Diskussion irgendwie `modulsammlung` ziemlich gut und könnte mir vorstellen, dass man die Templates weglässt, um es präzise zu behalten :)

Sollten mal Templates dazukommen wollen, könnte man ja auch ein neues Addon `templatesammlung` bauen?

**Comment by olien** [comment]
äre auch möglich... ok. es bleibt bei

`modulsammlung`

**Comment by tbaddade** [comment]
for-sammlung

**Comment by olien** [comment]
Es bleibt "Modulsammlung"... Done!

**Comment by olien** [comment]
Ok. Jetzt gibt es doch die Möglichkeit Templates hinzuzufügen....  :-)

Was machen wir nun?

**Comment by schuer** [comment]
Ich würde die Modulsammlung so lassen und stattdessen ein zweites Addon »Templatesammlung« bauen.

**Comment by alexplusde** [comment]
Ich bin jetzt mal gemein...

Addon: Sammlung 
Plugins: Modulsammlung, Templatesammlung

**Comment by olien** [comment]
Und dann 

Sammelsurium

nennen?

**Comment by skerbis** [comment]
Collection

**Comment by alexplusde** [comment]
Vorlagen? Beispiele?

**Comment by skerbis** [comment]
Module und Templates = MuT

**Comment by olien** [comment]
Awesome collection

**Comment by alexplusde** [comment]
Onkel Oli's Wundertüte.

**Comment by gseilheimer** [comment]
for_bimmelbam_by_oli

**Comment by olien** [comment]
Ich glaub ich mach das mal zu....
