### ISSUE TITLE
Qualität der Module?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/Modulsammlung#60]
Hallo Zusammen,

vielleicht könnten wir mal festlegen was ein Modul grundsätzlich für Eigenschaften haben sollte.
Z.B.: welche Editoren (eigenes Profil?) soll es unterstützen sofern eine Textarea vorhanden ist?

Auch wäre es schön ein einheitliches Layout fürs Backend (edit und normale Anzeige) zu finden. Gefällt euch das jetzt wie es ist? 

LG
Oliver

**Comment by skerbis** [comment]
So sehe ich das: 
Die Eingaben der Module sollten die "Redaxo"-eigenen Bootstrap-Stile/Elemente benutzen, soweit möglich. Daher auf zusätzliches inline CSS verzichten. 

Bei den Editoren würde ich eine Lösung bevorzugen, die es mir ermöglicht, diese schnell im Code auszutauschen. Mal hat der Kunde lieber einen WYSIWYG mal ist Textile oder Markdown angebracht. 
Wenn das Modul gut kommentiert ist, ist es kein Problem. ;-)

**Comment by olien** [comment]
Find ich gut so. Gibt es sonst noch Meinungen?

**Comment by olien** [comment]
War mir jetzt etwas zu wenig Feedback. Auch wenn Du recht hast Thomas schliesse ich das hier erst einmal. Module können ja gerne von jedem angepasst werden!
