### ISSUE TITLE
Anpassung der Ausgabe im Google Maps Modul

### ISSUE THREAD

**Issue by Markus-GS** [FriendsOfREDAXO/Modulsammlung#61]
Google meckert an, daß die "sensor"-Angabe in der Ausgabe nicht mehr ok ist von daher:

Moduleingabe:
`
if(typeof google === "undefined") {
loadScript('https://maps.googleapis.com/maps/api/js?<?php echo $gmapikey; ?>v=3&libraries=places&callback=initialize');
}
`

Modulausgabe:
`
if ($mapidx==''){
    echo '<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?'.$gmapikey.'&amp;language='.$sprache.'&amp;region='.strtoupper($sprache).'"></script>';
`

**Comment by olien** [comment]
Danke. werde ich ändern!

**Comment by olien** [comment]
Erledigt
