### ISSUE TITLE
Google Maps marker zentrieren responsive

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/Modulsammlung#66]
Hallo, ich habe das Modul Google Maps verwendet, habe aber damit der Marker bei Resize immer zentriert wird noch folgenden Code eingefügt ...

`google.maps.event.addDomListener(window, 'resize', function() {
    var center = map".$mapidx.".getCenter();
    google.maps.event.trigger(map".$mapidx.", 'resize');
    map".$mapidx.".setCenter(center); 
});`

vielleicht kann das jemand gebrauchen ... insert bei Zeile 110

**Comment by olien** [comment]
danke. baue ich ein...

**Comment by olien** [comment]
Ist in Version 4.7.0 eingebaut. Danke sehr!
