### ISSUE TITLE
zu Modul 0050 (Unite-Gallery): Fehler im CSS/JS-Einbau?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/Modulsammlung#70]
Hallo zusammen

mir ist aufgefallen, dass die Datei "unite-gallery.css" zweimal eingebunden wird: Zeile 1 und Zeile 5.

```<link  href="./assets/unitegallery/css/unite-gallery.css" type="text/css" rel="stylesheet"/>
<script src="./assets/unitegallery/themes/default/ug-theme-default.js" type="text/javascript"></script>
<link  href="./assets/unitegallery/themes/default/ug-theme-default.css" type="text/css" rel="stylesheet" />
<script src="./assets/unitegallery/js/unitegallery.min.js" type="text/javascript" ></script>
<link  href="./assets/unitegallery/css/unite-gallery.css" rel="stylesheet" type="text/css" />
<script src="./assets/unitegallery/themes/tiles/ug-theme-tiles.js" type="text/javascript"></script>
<script src="./assets/unitegallery/themes/tilesgrid/ug-theme-tilesgrid.js" type="text/javascript"></script>
```

Ist das ein spezieller Trick, um unerwünschte Änderungen aus Zeile 3 wieder zurückzusetzen, oder ein Versehen?

Grüße
Chris

**Comment by skerbis** [comment]
Ist sicher ein Versehen, zudem sollte der Code nicht in der Ausgabe sein. Er sollte selbst im Frontend eingebunden werden.

**Comment by christophboecker** [comment]
Beim Einbau ins Frontend ist es mir aufgefallen. :-)

**Comment by olien** [comment]
??

Die ug-theme-default.css und die unite-gallery.css sind doch unterschiedlich oder was meinst du?
Die Reihenfolge könnte schöner sein... ok

LG
Oliver

**Comment by skerbis** [comment]
@olien im Posting fehlt die 1. Zeile dann wird's klarer

**Comment by olien** [comment]
Ist erledigt. Danke
