### ISSUE TITLE
Variable in SCSS/CSS kann Foundation Setup stören

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/Modulsammlung#71]
Beim Einbau der Styles vom Modul "0820 - MBlock - MForm - Owl Carousel (Slider)" hat die Zeile

`background: $gray;`

mein ganzes Foundation 5 Setup zum "Absturz" gebracht. Es war eine lustige Kaskade: durch die unbekannte Variable hatte ich kein CSS mehr, wodurch JQuery einen seltsamen Fehler geworfen hat und ich stand vor der Website und war erstmal völlig ratlos.

Mein Vorschlag: $gray durch Farbe ersetzen, oder in der Docu drauf hinweisen, dass es zu seltsamen Fehlern kommen kann, wenn man nicht Framework XYZ benutzt.

**Comment by olien** [comment]
@elricco Ist das nicht deine Baustelle? :-)

**Comment by elricco** [comment]
Ja, ist es - werde ich mal fixen. Die Variable habe ich übersehen und nicht durch eine Farbe ersetzt- richtig.
