### ISSUE TITLE
Modulsammlung > Output?

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/Modulsammlung#78]
Hallo Oliver,

die Modulsammlung ist eine tolle Idee und hilft mir schon sehr, die input.php zu programmieren. Ergänzend schlage ich vor, auch Vorschläge für die output.php zu integrieren - zumindest für die Darstellung im Backend. Das Frontend muss dann ja ohnehin jeder adaptieren. 

Als Schema für's output schlage ich vor:

`<?php if(rex::isBackend()) : ?>`
 	
`	[hier die Ausgabe für's Backend]
	>> erstellt von der Community`

`<?php else : ?>`
    
`    [hier Deine Adaption für's Frontend]`
    
`<?php endif; ?>`

Was hältst Du davon?

Danke und viele Grüße,
Franziska

**Comment by olien** [comment]
Welche Module meinst Du genau?

**Comment by madiko** [comment]
Alle. ;-)
Bei mir steht jeweils nur

' <?php

echo '<pre>';
print_r(rex_var::toArray("REX_VALUE[1]"));
echo '</pre>';

?>'

**Comment by olien** [comment]
Hm. Alle????
Du kannst nur die MForm Module meinen.
Alle anderen haben Den Output für Front- und Backend.

Auf GitHub gibt es bei MForm eine Doku (Plugin). Da sollten die Erklärungen drin stehen.

**Comment by madiko** [comment]
Oh, stimmt! Da ich mich aktuell mit mform und mblock beschäftige, habe ich von diesen auf alle geschlossen. Hast Recht - bei den anderen steht was drin. Entschuldige bitte für den Schreck, den ich Dir vermutlich einjagte.

Leider ist die Doku zu mform noch sehr rudimentär und hilft mir nicht weiter. Ich muss alles über try&error ausprobieren. Da ich nicht firm im Programmieren bin, ist das sehr sehr sehr aufwändig und frustrierend, weil ich oft nicht weiß, _warum_ etwas nicht funktioniert.

**Comment by olien** [comment]
Tipp: beschäftige dich erst einmal nur mit MForm und frage vielleicht Joachim nach einer mini Output Demo.

Das Modul OWL-Carousel von Tim hat übrigens (wahrscheinlich umfangreichen) Output.

LG
Oliver

**Comment by olien** [comment]
Ich denke das kann hier zu...
