### ISSUE TITLE
17 . Text / Bild / Video / Link (1-4 Spalten)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/Modulsammlung#85]
Hi, ich habe gerade Dein Modul *17 . Text / Bild / Video / Link (1-4 Spalten)* aus der Modulsammlung verwendet. Unter PHP 7.1 kommt dann folgende Meldung: `Warning: A non-numeric value encountered in rex:///module/17/output on line 76`
Zeile 76 ist `$zaehler = $zaehler + 1;` $zaehler ist in Zeile 11 definiert. Wenn man danach mit `settype($zaehler, "integer");` einen Integer-Typ für $zaehler festlegt, ist die Meldung behoben.
Hintergrund ist wohl das hier: http://php.net/manual/de/migration71.other-changes.php

Danke an Flo

**Comment by tbaddade** [comment]
>  $zaehler ist in Zeile 11 definiert.

Ist dort ein string ` $zaehler = ''`. 
Mach mal `$zaehler = 0`.
