### ISSUE TITLE
Aktualisierung der Modulsammlung

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/Modulsammlung#87]
Hallo, 

ich möchte in den nächsten Wochen die Modulsammlung aktualisieren.
Habt Ihr dazu Wünsche / Ideen?

Fehlt was? Soll etwas raus?

Freue mich über Feedback.
Oliver

**Comment by olien** [comment]
Wie wäre es mit einem Reiter "Module für spezielle AddOns"?

Mögt Ihr etwas dazu beitragen?

z.B.:
* coole yorm Beispiele
* sked Ausgaben 
* etc.

**Comment by olien** [comment]
Es könnte auch noch ein Reiter für Beispiel-Tablesets entstehen...

Dann benennen wir das Dingen  um in Starter-Kit :-)

**Comment by skerbis** [comment]
Denke gerade darüber nach die UIKit Module zu überführen

**Comment by olien** [comment]
Wäre auch ok.

Wobei wir mal überlegen sollte ob die Modulsammlung "nur" Beispiele aufzeigt oder Tatsächlich fertige Module für unterschiedliche Bereiche (Bootstrap, UIKit, Foundation etc..) liefern soll... Ich würde das Dingen Kopieren und nen UIKIt-Module Addon draus machen.

**Comment by skerbis** [comment]
Das gibt es schon https://github.com/FriendsOfREDAXO/uikit_collection 
Komme aber nicht dazu weiterzumachen

**Comment by olien** [comment]
Hier macht leider auch kaum jemand mit.... es hätte so groß werden können :-))

**Comment by olien** [comment]
OK. Da nicht wirklich was kommt mache ich wie ich meine und mache das hier zu... 
Mag offene Issues nicht :-))
