### ISSUE TITLE
Umstellung aller Module auf ein bestimmtest Gridsystem?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/Modulsammlung#91]
- https://getbootstrap.com/docs/4.1/utilities/flex/ (B4 Flex)
- https://getbootstrap.com/docs/4.0/layout/grid/ (B4)
- https://foundation.zurb.com/grid.html (Foundation)
- https://gridlex.devlint.fr (Gridlex)
.
.

**Comment by olien** [comment]
Ist das dann noch für Einsteiger?
(Die MInibeispiele bekommen sowieso kaum Frontend HTML)

**Comment by tbaddade** [comment]
> Ist das dann noch für Einsteiger?

Ich denke schon.
Vielleicht könnte man damit auch die Erfahrenen abholen. So dass das AddOn tatsächlich als Sammlung aller dient und eher als "ModuleInstaller" genutzt wird.

**Comment by olien** [comment]
Magst du mir mal ein Beispiel schicken?
Eilt nicht.

**Comment by skerbis** [comment]
Das macht das Ganze schon relativ aufwendig in der Pflege. Es werden schnell Fragen aufkommen wie: warum ist Framework xy nicht dabei?

**Comment by olien** [comment]
Das befürchte ich nicht wirklich. Seit November 2015 wurde der ausgegebene Quelltext nie angesprochen soweit ich mich erinnern kann...
