### ISSUE TITLE
Modulidee: Fake Statistiken (so Kreise mit Zahlen halt...)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/Modulsammlung#93]

**Comment by olien** [comment]
so etwas

![image](https://user-images.githubusercontent.com/330516/45156022-2f0bee80-b1dd-11e8-9529-6ae6a62342fd.png)

**Comment by skerbis** [comment]
Wann denn? @olien

**Comment by olien** [comment]
Braucht das denn noch jemand?

**Comment by skerbis** [comment]
hihi

**Comment by olien** [comment]
Kein Kommentar
