### ISSUE TITLE
Call to a member function getAttribute() on null in Modul 

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/Modulsammlung#95]
Redaxo: 5.6.4
Modulsammlung: 4.11.0
MBlock: 2.2.3

Beim Bearbeiten von bestehenden Modulen, oder beim Erstellen eines neuen Slice mit dem Modul, wird der Fehler ausgelöst. 

![image](https://user-images.githubusercontent.com/196336/47991983-fb214c80-e0eb-11e8-9606-a037bf25dd40.png)

**Comment by olien** [comment]
Gabe es hierzu eine Lösung im slack? Habs vergessen :-(

**Comment by olien** [comment]
Ist das noch aktuell? Den Fehler hatte ich nie...

**Comment by omphteliba** [comment]
Nein, das Problem konnte ich nicht mehr reproduzieren.

**Comment by olien** [comment]
Dann mache ich das zu. Danke!
